# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-19 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('max_capacity', models.IntegerField(default=0)),
                ('model_description', models.TextField(blank=True, help_text='Enter a brief description of the Truck Model', max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Truck_Model',
                'verbose_name_plural': 'Truck_Models',
            },
        ),
        migrations.CreateModel(
            name='TruckNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bort_number', models.CharField(max_length=20)),
                ('truck_number_description', models.TextField(blank=True, help_text='Enter a brief description of the Truck Number', max_length=1000, null=True)),
                ('current_weight', models.IntegerField(default=0)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_work_start_date', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.TruckModel')),
            ],
            options={
                'verbose_name': 'Truck_Number',
                'verbose_name_plural': 'Truck_Numbers',
            },
        ),
    ]
